{-|
  Project Euler Problem: 002
  Link: Link: https://projecteuler.net/problem=2

  Each new term in the Fibonacci sequence is generated by adding the previous
  two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not
  exceed four million, find the sum of the even-valued terms.
-}

-- Using the infinite list of Fibonacci numbers
fibs = 0 : 1 : zipWith (+) fibs (tail fibs)

euler002 = sum [n | n <- takeWhile (< 4000000) fibs, even n]
